Consensys/gnark-crypto

- bls377/g1.go
- bls377/g2.go
- bls377/pairing.go
- bls377/pairing_test.go
- bls381/g1.go
- bls381/g2.go
- bls381/interop_test.go
- bls381/pairing.go
- bls381/pairing_test.go
- bn256/g1.go
- bn256/g2.go
- bn256/interop_test.go
- bn256/pairing.go
- bn256/pairing_test.go
- bw761/g1.go
- bw761/g2.go
- internal/templates/pairing/tests/pairing.go.tmpl
- internal/templates/point/point.go.tmpl
- Mutualize squaring inside the Miller loops
- PairingCheck
- Tests
> Pairing of a set of points (bn, bls12)

- bls377/pairing.go
- bls381/pairing.go
hard part following: Daiki Hayashida, Kenichiro Hayasaka, and Tadanori Teruya 2020 https://eprint.iacr.org/2020/875.pdf
> BLS12 final exponentiation (eprint 2020/875)

- ecc/bls12-377/fp/element.go
- ecc/bls12-377/fp/element_test.go
- ecc/bls12-377/fr/element.go
- ecc/bls12-377/fr/element_test.go
- ecc/bls12-381/fp/element.go
- ecc/bls12-381/fp/element_test.go
- ecc/bls12-381/fr/element.go
- ecc/bls12-381/fr/element_test.go
- ecc/bls24-315/fp/element.go
- ecc/bls24-315/fp/element_test.go
- ecc/bls24-315/fr/element.go
- ecc/bls24-315/fr/element_test.go
- ecc/bn254/fp/element.go
- ecc/bn254/fp/element_test.go
- ecc/bn254/fr/element.go
- ecc/bn254/fr/element_test.go
- ecc/bw6-633/fp/element.go
- ecc/bw6-633/fp/element_test.go
- ecc/bw6-633/fr/element.go
- ecc/bw6-633/fr/element_test.go
- ecc/bw6-761/fp/element.go
- ecc/bw6-761/fp/element_test.go
- ecc/bw6-761/fr/element.go
- ecc/bw6-761/fr/element_test.go
- field/internal/templates/element/inverse.go
- field/internal/templates/element/inverse_tests.go
> style: remove redundant check

- ecc/bls12-377/fr/fft/domain.go
Just stumpled upon some useless code.
> Remove some useless code in fft.NewDomain

- ecc/bls12-377/fr/fft/domain.go
- ecc/bls12-381/fr/fft/domain.go
- ecc/bls24-315/fr/fft/domain.go
- ecc/bn254/fr/fft/domain.go
- ecc/bw6-633/fr/fft/domain.go
- ecc/bw6-761/fr/fft/domain.go
- internal/generator/fft/template/domain.go.tmpl
Cleaning the template and `go generate ./...`
> Fix/fft `FrMultiplicativeGen`

- ecc/bn254/twistededwards/eddsa/eddsa.go
https://github.com/ConsenSys/gnark-crypto/issues/199
> Update endian revert process logic

- utils/decompose.go
Moved from https://github.com/ConsenSys/gnark/pull/398 .
> add Decompose

- ecc/bls12-377/fp/element.go
- ecc/bls12-377/fr/element.go
- ecc/bls12-378/fp/element.go
- ecc/bls12-378/fr/element.go
- ecc/bls12-381/fp/element.go
- ecc/bls12-381/fr/element.go
- ecc/bls24-315/fp/element.go
- ecc/bls24-315/fr/element.go
- ecc/bls24-317/fp/element.go
- ecc/bls24-317/fr/element.go
- ecc/bn254/fp/element.go
- ecc/bn254/fr/element.go
- ecc/bw6-633/fp/element.go
- ecc/bw6-633/fr/element.go
- ecc/bw6-756/fp/element.go
- ecc/bw6-756/fr/element.go
- ecc/bw6-761/fp/element.go
- ecc/bw6-761/fr/element.go
- ecc/secp256k1/fp/element.go
- ecc/secp256k1/fr/element.go
- ecc/secp256k1/fr/polynomial/multilin.go
- ecc/secp256k1/fr/polynomial/polynomial.go
- ecc/secp256k1/fr/polynomial/polynomial_test.go
- ecc/secp256k1/fr/polynomial/pool.go
- field/generator/internal/templates/element/conv.go
- field/goldilocks/element.go
- internal/generator/gkr/generate.go
- internal/generator/main.go
cherry picked @jsign commits from #292 + rebase on develop.
> avoid big.Int assign see #292

- ecc/bls12-377/fp/element.go
- ecc/bls12-377/fr/element.go
- ecc/bls12-378/fp/element.go
- ecc/bls12-378/fr/element.go
- ecc/bls12-381/fp/element.go
- ecc/bls12-381/fr/element.go
- ecc/bls24-315/fp/element.go
- ecc/bls24-315/fr/element.go
- ecc/bls24-317/fp/element.go
- ecc/bls24-317/fr/element.go
- ecc/bn254/fp/element.go
- ecc/bn254/fr/element.go
- ecc/bw6-633/fp/element.go
- ecc/bw6-633/fr/element.go
- ecc/bw6-756/fp/element.go
- ecc/bw6-756/fr/element.go
- ecc/bw6-761/fp/element.go
- ecc/bw6-761/fr/element.go
- ecc/secp256k1/fp/element.go
- ecc/secp256k1/fr/element.go
- ecc/stark-curve/fp/element.go
- ecc/stark-curve/fr/element.go
- field/generator/internal/templates/element/base.go
- field/goldilocks/element.go
See #306  for issue; seems its not used in gnark-crypto or gnark anyway... so killed it.
> nuke element.Bit() fixes #306

- zkalc.sh
Add benchmarking code for FFTs.
> zkalc: Add FFT benchmark

- ecc/bls12-381/bls12-381.go
Needed to test BLS12-381 pairing in gnark
> Expose BLS12-381 tower

- ecc/bls12-377/fr/kzg/kzg.go
- ecc/bls12-378/fr/kzg/kzg.go
- ecc/bls12-381/fr/kzg/kzg.go
- ecc/bls24-315/fr/kzg/kzg.go
- ecc/bls24-317/fr/kzg/kzg.go
- ecc/bn254/fr/kzg/kzg.go
- ecc/bw6-633/fr/kzg/kzg.go
- ecc/bw6-756/fr/kzg/kzg.go
- ecc/bw6-761/fr/kzg/kzg.go
- internal/generator/kzg/template/kzg.go.tmpl
> fix(kzg): nb of digests in BatchVerifyMultiPoints should be nonzeo

- ecc/bls12-377/fr/pedersen/pedersen.go
- ecc/bls12-377/fr/pedersen/pedersen_test.go
- ecc/bls12-378/fr/pedersen/pedersen.go
- ecc/bls12-378/fr/pedersen/pedersen_test.go
- ecc/bls12-381/fr/pedersen/pedersen.go
- ecc/bls12-381/fr/pedersen/pedersen_test.go
- ecc/bls24-315/fr/pedersen/pedersen.go
- ecc/bls24-315/fr/pedersen/pedersen_test.go
- ecc/bls24-317/fr/pedersen/pedersen.go
- ecc/bls24-317/fr/pedersen/pedersen_test.go
- ecc/bn254/fr/pedersen/pedersen.go
- ecc/bn254/fr/pedersen/pedersen_test.go
- ecc/bw6-633/fr/pedersen/pedersen.go
- ecc/bw6-633/fr/pedersen/pedersen_test.go
- ecc/bw6-756/fr/pedersen/pedersen.go
- ecc/bw6-756/fr/pedersen/pedersen_test.go
- ecc/bw6-761/fr/pedersen/pedersen.go
- ecc/bw6-761/fr/pedersen/pedersen_test.go
- internal/generator/pedersen/template/pedersen.go.tmpl
- internal/generator/pedersen/template/pedersen.test.go.tmpl
The same as https://github.com/ConsenSys/gnark-crypto/pull/383 but with no fp tower modifications.
> refactor: break pedersen key into proving (committing) and verifying

- field/hash/hashutils.go
> doc: update hash to curve rfc ref and impl comment

- ecc/bls12-377/fr/fft/domain.go
- ecc/bls12-381/fr/fft/domain.go
- ecc/bls24-315/fr/fft/domain.go
- ecc/bls24-317/fr/fft/domain.go
- ecc/bn254/fr/fft/domain.go
- ecc/bw6-633/fr/fft/domain.go
- ecc/bw6-761/fr/fft/domain.go
- internal/generator/fft/template/domain.go.tmpl
- **refactor: change fft domain encoder to not use ecc one**
- **refactor: remove dependency on ecc encoder in fft domain**
> refactor: remove dependency on ecc Encoder in fft domain marshal

- ecc/bls12-377/fp/doc.go
- ecc/bls12-377/fr/doc.go
- ecc/bls12-381/fp/doc.go
- ecc/bls12-381/fr/doc.go
- ecc/bls24-315/fp/doc.go
- ecc/bls24-315/fr/doc.go
- ecc/bls24-317/fp/doc.go
- ecc/bls24-317/fr/doc.go
- ecc/bn254/fp/doc.go
- ecc/bn254/fr/doc.go
- ecc/bw6-633/fp/doc.go
- ecc/bw6-633/fr/doc.go
- ecc/bw6-761/fp/doc.go
- ecc/bw6-761/fr/doc.go
- ecc/secp256k1/fp/doc.go
- ecc/secp256k1/fr/doc.go
- ecc/stark-curve/fp/doc.go
- ecc/stark-curve/fr/doc.go
- field/babybear/doc.go
- field/generator/internal/templates/element/doc.go
- field/goldilocks/doc.go
- field/koalabear/doc.go
Adds uint32/uint64 differentiation + notification of vectorized ops + reference to audit list.
> docs: update element package doc

- ecc/bls12-377/fr/fft/domain.go
- ecc/bls12-377/fr/fri/fri_test.go
- ecc/bls12-381/fr/fft/domain.go
- ecc/bls12-381/fr/fri/fri_test.go
- ecc/bls24-315/fr/fft/domain.go
- ecc/bls24-315/fr/fri/fri_test.go
- ecc/bls24-317/fr/fft/domain.go
- ecc/bls24-317/fr/fri/fri_test.go
- ecc/bn254/fr/fft/domain.go
- ecc/bn254/fr/fri/fri_test.go
- ecc/bw6-633/fr/fft/domain.go
- ecc/bw6-633/fr/fri/fri_test.go
- ecc/bw6-761/fr/fft/domain.go
- ecc/bw6-761/fr/fri/fri_test.go
- field/generator/internal/addchain/addchain.go
- internal/generator/fft/template/domain.go.tmpl
- internal/generator/fri/template/fri.test.go.tmpl
fix some function names in comment
Fixes # (issue)
> chore: fix some function names in comment

- ecc/bls12-377/fr/mimc/doc.go
- ecc/bls12-381/fr/mimc/doc.go
- ecc/bls24-315/fr/mimc/doc.go
- ecc/bls24-317/fr/mimc/doc.go
- ecc/bn254/fr/mimc/doc.go
- ecc/bw6-633/fr/mimc/doc.go
- ecc/bw6-761/fr/mimc/doc.go
- ecc/ecc.md
- internal/generator/crypto/hash/mimc/template/doc.go.tmpl
I hope my corrections will be helpful and contribute to improving your work. Thank you for your dedication and effort.
> Corrected spelling and grammar mistakes

- ecc/bls12-377/fr/gkr/gkr.go
- ecc/bls12-377/fr/sumcheck/sumcheck.go
- ecc/bls12-381/fr/gkr/gkr.go
- ecc/bls12-381/fr/sumcheck/sumcheck.go
- ecc/bls24-315/fr/gkr/gkr.go
- ecc/bls24-315/fr/sumcheck/sumcheck.go
- ecc/bls24-317/fr/gkr/gkr.go
- ecc/bls24-317/fr/sumcheck/sumcheck.go
- ecc/bn254/fr/gkr/gkr.go
- ecc/bn254/fr/sumcheck/sumcheck.go
- ecc/bw6-633/fr/gkr/gkr.go
- ecc/bw6-633/fr/sumcheck/sumcheck.go
- ecc/bw6-761/fr/gkr/gkr.go
- ecc/bw6-761/fr/sumcheck/sumcheck.go
- internal/generator/gkr/template/gkr.go.tmpl
- internal/generator/sumcheck/template/sumcheck.go.tmpl
- internal/generator/test_vector_utils/small_rational/gkr/gkr.go
- internal/generator/test_vector_utils/small_rational/sumcheck/sumcheck.go
use errors.New to replace fmt.Errorf with no parameters
> chore: use errors.New to replace fmt.Errorf with no parameters

- field/generator/config/fft_config.go
fix problematic function name in comment
> chore: fix problematic function name in comment

- README.md
- field/generator/config/fft_config.go
This PR collects typo fix PRs to be squashed before merging to master.
Ready - good to be merged on my side.
> typos: squashed typo fixes

- ecc/bls12-377/fr/poseidon2/poseidon2.go
- ecc/bls12-381/fr/poseidon2/poseidon2.go
- ecc/bls24-315/fr/poseidon2/poseidon2.go
- ecc/bls24-317/fr/poseidon2/poseidon2.go
- ecc/bn254/fr/poseidon2/poseidon2.go
- ecc/bw6-633/fr/poseidon2/poseidon2.go
- ecc/bw6-761/fr/poseidon2/poseidon2.go
- internal/generator/crypto/hash/poseidon2/template/poseidon2.go.tmpl
Just adjusting some loop boundaries
> fix: missing Poseidon2 round keys
