bls377/g1.go, bls377/g1_test.go, bls381/g1.go, bls381/g1_test.go, bn256/g1.go, bn256/g1_test.go, internal/generators/template/generator/generator.go
We recently became aware that GLV point multiplication is encumbered by patent.  This PR removes support for GLV point multiplication so as not to infringe upon the patent.  The patent has expired everywhere except in the USA, where it is set to expire in September 2020.  We can re-enable support for GLV point multiplication after the patent has expired everywhere.
=> Remove support for GLV point multiplication

bls377/pairing.go, bls381/pairing.go, bn256/pairing.go
Issue: #13 
Replace 6-th Frobenius power by unitary inverse in BN254, BLS12-377 and BLS12-381
**TODO**
Same goes for BW6-761 especially that it uses many `FrobeniusCube` in the hard part, but it seems that BW6 `GT`is implemented as `Fp3over2` rather than `Fp2over3`.
=> replace k/2-th Frobenius powers by conjugations

bls381/internal/fptower/e12_pairing.go, bls381/pairing.go
Since the `bls12-381` seed is even, this PR implements Alg.2 from https://eprint.iacr.org/2016/130.pdf. 
This saves 2 multiplications and 2 squares in `Fq12`, and 2 temporary variables. 
According to `BenchmarkFinalExponentiation`, this saves around `127336 ns/op`.
=> Optimize BLS12-381 final exponentiation

bls377/internal/fptower/e12.go, bls381/internal/fptower/e12.go, bn256/internal/fptower/e12.go, internal/templates/fq12over6over2/fq12.go.tmpl
see fq12.go tempalte --> removed one `MulByNonResidueInv` (cancelling with `MulByNonResidue`) and used E2 squaring (significantly faster than e2 mul) in fp4square . 
on my machine: 
```
benchmark              old ns/op     new ns/op     delta
BenchmarkPairing-8     903356        827455        -8.40%
BenchmarkPairing-8     907516        823723        -9.23%
```
=> fp12: improved cyclotomicSquare

README.md, bls377/pairing.go, bls381/pairing.go, bn256/pairing.go
@yelhousni following your recent awesome PR (#26) did some experiments and benchmarks on various architectures (x64), that confirms that for a small number of pair of points in the `Pairing` function, there is a severe penalty (specifically on `amd` platforms). 
In this PR, I just removed the go routines, the multiple `[68]lineEvaluation` (replace by a single `lineEvaluation` object) and merged the `preCompute` loop within the line evaluation / result compute loop. Did on `bn256` and `bls381`.
** If we want to deal with large number of pairs in `Pairing`, then we should probably revisit the `preCompute` strategy ** 
Here is where we're at on our reference benchmark (running on AWS z1d.3xlarge instance, with hyperthreading disabled) :
||mcl(ns/op)|gurvy(ns/op)|
| -------- | -------- | …
=> Pairing: remove preCompute and go routines in MillerLoop

ecc/bls12-377/fr/fft/fft.go, ecc/bls12-381/fr/fft/fft.go, ecc/bn254/fr/fft/fft.go, ecc/bw6-761/fr/fft/fft.go, internal/generator/fft/template/fft.go.tmpl
Missed that in my review of #45 . 
The pattern 
```
BitReverse(domain.CosetTableInv[coset-1])
// ...  scale by coset
BitReverse(domain.CosetTableInv[coset-1])
```
is not thread safe, and quite wasteful. 
Replaced by dynamically computing the correct index in the coset table:
```
parallel.Execute(len(a), func(start, end int) {
for i := start; i < end; i++ {
irev := bits.Reverse64(uint64(i)) >> nn
a[i].Mul(&a[i], &domain.CosetTable[coset-1][int(irev)])
}
})
```
Benchmark: 
```
BenchmarkFFT/fft_2**19bits_(cosets_without_precomputations)-8     63984013      43923680      -31.35%
```
Also did few style adjustment with less if -> if -> else -> if statements.
=> fix: fft domain precompute thread safety

ecc/bls12-377/internal/fptower/e12.go, ecc/bls12-377/pairing_test.go, ecc/bls12-381/internal/fptower/e12.go, ecc/bls12-381/pairing_test.go, ecc/bn254/internal/fptower/e12.go, ecc/bn254/pairing_test.go, ecc/bw6-761/internal/fptower/e6.go, ecc/bw6-761/pairing_test.go, internal/generator/pairing/template/tests/pairing.go.tmpl, internal/generator/tower/template/fq12over6over2/fq12.go.tmpl
- BN:
`g^(6*u^2) == g^p` 
- BLS12:
`g^(p^4+1) == g^(p^2) && g^p == g^u`
- BW6:
`g^(p^2+1) == g^p && g^(3p) == g^(13u^6 − 23u^5 − 9u^4 + 35u^3 + 10u + 19)`
Using Granger-Scott `CyclotomicSquare`, and `Conjugate` for inverse once the first check is verified (`g` in the cyclotomic subgroup).
=> faster GT membership

ecc/bls12-381/internal/fptower/e12_pairing.go, ecc/bls12-381/pairing.go
leveraging on #106 and using Karabina's cyclotomic squaring for two series of 0 (#75) with a batch decompression, we can improve BLS12-381 final exponentiation.
```
benchmark                           old ns/op     new ns/op     delta
BenchmarkFinalExponentiation-32     424414        395896        -6.72%
```
=> perf: Final exp. on BLS12-381

ecc/bls12-377/fr/element_mul_adx_amd64.s, ecc/bls12-377/fr/element_mul_amd64.s, ecc/bls12-381/fr/element_mul_adx_amd64.s, ecc/bls12-381/fr/element_mul_amd64.s, ecc/bls24-315/fp/element_mul_adx_amd64.s, ecc/bls24-315/fp/element_mul_amd64.s, ecc/bls24-315/fr/element_mul_adx_amd64.s, ecc/bls24-315/fr/element_mul_amd64.s, ecc/bn254/fp/element_mul_adx_amd64.s, ecc/bn254/fp/element_mul_amd64.s, ecc/bn254/fr/element_mul_adx_amd64.s, ecc/bn254/fr/element_mul_amd64.s, ecc/bw6-633/fr/element_mul_adx_amd64.s, ecc/bw6-633/fr/element_mul_amd64.s, field/asm/amd64/element_frommont.go, field/asm/amd64/element_mul.go
This PR supersedes #112 .
Addresses #113 for small moduli only (<= 5  words).
=> fix: remove use of R15 for small moduli mul #113

ecc/bls12-377/g1_test.go, ecc/bls12-377/g2.go, ecc/bls12-377/g2_test.go, ecc/bls12-381/g1_test.go, ecc/bls12-381/g2.go, ecc/bls12-381/g2_test.go, ecc/bls24-315/g1_test.go, ecc/bls24-315/g2.go, ecc/bls24-315/g2_test.go, ecc/bn254/g1_test.go, ecc/bn254/g2_test.go, ecc/bw6-633/g1_test.go, ecc/bw6-633/g2_test.go, ecc/bw6-761/g1_test.go, ecc/bw6-761/g2_test.go, internal/generator/ecc/template/point.go.tmpl, internal/generator/ecc/template/tests/point.go.tmpl
=> perf(bls24-315): faster G2 membership test

ecc/bls12-377/fp/element.go, ecc/bls12-377/fp/element_test.go, ecc/bls12-377/fr/element.go, ecc/bls12-377/fr/element_test.go, ecc/bls12-381/fp/element.go, ecc/bls12-381/fp/element_test.go, ecc/bls12-381/fr/element.go, ecc/bls12-381/fr/element_test.go, ecc/bls24-315/fp/element.go, ecc/bls24-315/fp/element_test.go, ecc/bls24-315/fr/element.go, ecc/bls24-315/fr/element_test.go, ecc/bn254/fp/element.go, ecc/bn254/fp/element_test.go, ecc/bn254/fr/element.go, ecc/bn254/fr/element_test.go, ecc/bw6-633/fp/element.go, ecc/bw6-633/fp/element_test.go, ecc/bw6-633/fr/element.go, ecc/bw6-633/fr/element_test.go, ecc/bw6-761/fp/element.go, ecc/bw6-761/fp/element_test.go, ecc/bw6-761/fr/element.go, ecc/bw6-761/fr/element_test.go, field/internal/templates/element/base.go, field/internal/templates/element/tests.go
Slightly faster than `Equals` on small moduli, up to %50 slower on big ones
May be useful in algorithms advertised as c-time like sswu hash
=> feat: constant time Equal with tests and benchmarks

ecc/bls12-377/twistededwards/eddsa/eddsa.go, ecc/bls12-378/twistededwards/eddsa/eddsa.go, ecc/bls12-381/bandersnatch/eddsa/eddsa.go, ecc/bls12-381/twistededwards/eddsa/eddsa.go, ecc/bls24-315/twistededwards/eddsa/eddsa.go, ecc/bls24-317/twistededwards/eddsa/eddsa.go, ecc/bn254/twistededwards/eddsa/eddsa.go, ecc/bw6-633/twistededwards/eddsa/eddsa.go, ecc/bw6-756/twistededwards/eddsa/eddsa.go, ecc/bw6-761/twistededwards/eddsa/eddsa.go, internal/generator/edwards/eddsa/template/eddsa.go.tmpl
- Update endian revert process logic
- fix: closes #199. Correct bound in eddsa key gen template
See also #200 --> keeping commit [014a9cf](https://github.com/ConsenSys/gnark-crypto/pull/202/commits/014a9cfdefaa48442d6f03de29ae4f87bf25fb0b) but reported modif to template generation for all curves.
=> fix: closes #199 correct bound in eddsa key gen template

internal/field/field.go, utils/supsub.go
Integrate the superscript and subscript functions into gnark-crypto (superscript is useful for pretty printing of polynomials)
=> feat: supsub

ecc/bls12-377/g1.go, ecc/bls12-377/g2.go, ecc/bls12-378/g1.go, ecc/bls12-378/g2.go, ecc/bls12-381/g1.go, ecc/bls12-381/g2.go, ecc/bls24-315/g1.go, ecc/bls24-315/g2.go, ecc/bls24-317/g1.go, ecc/bls24-317/g2.go, ecc/bn254/g1.go, ecc/bn254/g2.go, ecc/bw6-633/g1.go, ecc/bw6-633/g2.go, ecc/bw6-756/g1.go, ecc/bw6-756/g2.go, ecc/bw6-761/g1.go, ecc/bw6-761/g2.go, internal/generator/ecc/template/point.go.tmpl
The 4 muls needed to check operands equality in ext-Jac add function should be re-used after that.
=> [perf] save 4 muls in ext-Jac add

ecc/bn254/fr/tensor-commitment/commitment.go, ecc/bn254/fr/tensor-commitment/commitment_test.go, go.mod, go.sum
Creates a struct `TcParams` that contains all the static parameters of the tensor commitment. The justification is that the parameters of this struct do not have the same lifecycle as the parameters of the `TcCommitment` struct which are used only for creating "1 instance of the commitment". It is a prerequisite for parallelization.
This allows the user-level parallelization by appending several columns at the same time. An alternative is to let the user pass several columns at the same time and do the parallelization internally. In this case, there is no need for the `pos` parameter.
Those steps happens at different interaction rounds thus they cannot be exposed in a single function if that function does not do the Fiat-Shamir hashes as well. Two APIs are possible
* Letting the user do …
=> Changes on SIS and tensor commitment resulting from the integration

ecc/bls12-377/g2.go, ecc/bls12-378/g2.go, ecc/bls12-381/g2.go, ecc/bls24-315/g2.go, ecc/bls24-317/g2.go, ecc/bn254/bn254.go, ecc/bn254/g2.go, internal/generator/ecc/template/point.go.tmpl
- https://eprint.iacr.org/2022/348.pdf (sec. 3 and 5.1)
- https://ethresear.ch/t/fast-mathbb-g-2-subgroup-check-in-bn254/13974
=> [perf] Faster G2 subgroup membership on BN254

ecc/bn254/fr/sis/experiment_prereduction_test.go, ecc/bn254/fr/sis/sis.go, ecc/bn254/fr/sis/sis_test.go, ecc/bn254/fr/tensor-commitment/commitment.go, ecc/bn254/fr/tensor-commitment/commitment_test.go
Also include a small-experiment, which lives in an isolated test file. The experiment underlines an idea to speed-up the SIS hashes down to 300ns per field element. It is however incomplete in the sense that it does not implement everything. Only the parts that are relevant "performance-wise" have been implemented.
The experiment is deeply tied to the choices of parameters that we use for SIS. (Recall d = 2 and \beta = 8). We do several thing. Instead, of representing "slots" in the hashing key with 2 field elements (internally represented as 4 uint64 each), we represent them using 6 uint64 limbs as follows.
```
0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff
represented as
0x00000fffffffffff
0x00000fffffffffff
0x00000fffffffffff
0x00000fffffffffff
0x00000fffffffffff …
```
=> Add support for parallelization in the tensor-commitment

ecc/bw6-756/internal/fptower/e6.go
Instead of checking `z^r==1` in GT (where `r` is 378 bit), we do the following sequential check:
- `z^(Phi_k(p)) == 1` (where `Phi_k(p)` is the kth-cyclotomic polynomial) and
- `z^(p+1-t) == 1` where `t`, the Frobenius trace, happens to be defined by the polynomial `t(x) = (-x⁶ + 5x⁵ - 9x⁴ + 7x³ - 4x + 5)/3 + 1` in the case of the BW6-756 curve
=> perf(bw6-756): optimize GT subgroup membership

ecc/bn254/bn254.go
needed for testing emulated bn254 tower fields in gnark https://github.com/ConsenSys/gnark/pull/532
=> expose bn254 tower to gnark

ecc/bls12-377/marshal.go, ecc/bls12-378/marshal.go, ecc/bls12-381/marshal.go, ecc/bls24-315/marshal.go, ecc/bls24-317/marshal.go, ecc/bn254/marshal.go, ecc/bw6-633/marshal.go, ecc/bw6-756/marshal.go, ecc/bw6-761/marshal.go, internal/generator/ecc/template/marshal.go.tmpl
Thanks to @asanso and @kevaundray for reporting; 
IETF spec we followed states:
> The serialization of a point at infinity comprises a string of zero bytes, except that the metadata bits may be nonzero.[¶](https://datatracker.ietf.org/doc/html/draft-irtf-cfrg-pairing-friendly-curves-11#appendix-C-3.3)
Previously, we did check the metadata bits and if they were signaling a point at infinity, discarded the rest of the buffer. We now add an additional check to ensure all the bytes are at 0.
=> fix: invalid infinity point decoding throws error

.github/workflows/pr.yml, README.md
The README indicates that `gnark-crypto` is tested on the latest two major releases. With the [recent release of Go 1.20](https://go.dev/doc/go1.20), these two versions should now be 1.19 and 1.20.
* Update the GitHub PR workflow with new versions.
* Also delete some trailing whitespace there.
* Update README to reflect this change.
* It was slightly out-of-date btw.
=> Run tests with Go 1.19 and 1.20

field/generator/config/field_test.go
Fixing two small bugs in the codegen-time field implementation test case generator
1. For fields of size 64n bits the word count was incorrectly computed as n+1
2. Sometimes the test case generator expected modulus bit length of size 1 or 0 bits.
=> fix: mods smaller than 5; overestimating nbword

ecc/bls12-377/internal/fptower/e12_pairing.go, ecc/bls12-377/internal/fptower/e6.go, ecc/bls12-377/pairing.go, ecc/bls12-378/internal/fptower/e12_pairing.go, ecc/bls12-378/internal/fptower/e6.go, ecc/bls12-378/pairing.go, ecc/bls12-381/internal/fptower/e12_pairing.go, ecc/bls12-381/internal/fptower/e6.go, ecc/bls12-381/pairing.go, ecc/bls24-315/internal/fptower/e24_pairing.go, ecc/bls24-315/pairing.go, ecc/bls24-317/internal/fptower/e12.go, ecc/bls24-317/internal/fptower/e24_pairing.go, ecc/bls24-317/pairing.go, ecc/bn254/internal/fptower/e12_pairing.go, ecc/bn254/internal/fptower/e6.go, ecc/bn254/pairing.go, ecc/bw6-633/internal/fptower/e6_pairing.go, ecc/bw6-633/pairing.go, ecc/bw6-756/internal/fptower/e6_pairing.go, ecc/bw6-756/pairing.go, ecc/bw6-761/internal/fptower/e6_pairing.go, ecc/bw6-761/pairing.go, internal/generator/tower/template/fq12over6over2/fq6.go.tmpl
Some refactoring and small optimisations of pairings ported from gnark.
=> Refactor: pairings

ecc/bn254/fr/sis/sis.go
*Returns a clone of the RSis parameters with a fresh and empty buffer. Does not mutate the current instance. The keys and the public parameters of the SIS instance are not deep-copied. It is useful when we want to hash in parallel. Otherwise, we would have to generate an entire RSis for each thread.*
=> Add `CopyWithFreshBuffer` a function to copy the state

ecc/stark-curve/pedersen-hash/pedersen_hash.go, ecc/stark-curve/pedersen-hash/pedersen_hash_test.go
Provides 5x performance improvement
=> Precompute point multiplication results in pedersen

ecc/bls12-377/fr/kzg/kzg.go, ecc/bls12-378/fr/kzg/kzg.go, ecc/bls12-381/fr/kzg/kzg.go, ecc/bls24-315/fr/kzg/kzg.go, ecc/bls24-317/fr/kzg/kzg.go, ecc/bn254/fr/kzg/kzg.go, ecc/bw6-633/fr/kzg/kzg.go, ecc/bw6-756/fr/kzg/kzg.go, ecc/bw6-761/fr/kzg/kzg.go, internal/generator/kzg/template/kzg.go.tmpl
This PR tradeoffs a scalar multiplication in **G2** for a scalar multiplication in **G1** in the case of KZG opening in a single point (`Verify` method). Kudos to @Tabaie for this observation.
```diff
-       // e([f(α) - f(a)]G₁, G₂).e([-H(α)]G₁, [α-a]G₂) ==? 1
+       // e([f(α)-f(a)+aH(α)]G₁], G₂).e([-H(α)]G₁, [α]G₂) == 1
```
We actually use KZG opening in multiple points (`BatchVerifyMultiPoints`) for PlonK. So this does not impact the PlonK verification time but only the public `Verify` method, which could be of independent interest. On AWS z1d.large:
```go
benchmark                       old ns/op     new ns/op     delta
BenchmarkKZGVerify-2            708830        653944        -7.74%
BenchmarkKZGBatchVerify10-2     1084355       1035049       -4.55%
```
=> Perf: KZG verification in a single point

ecc/bn254/ecdsa/ecdsa.go, ecc/bn254/ecdsa/marshal.go, ecc/secp256k1/ecdsa/ecdsa.go, ecc/secp256k1/ecdsa/marshal.go, ecc/stark-curve/ecdsa/ecdsa.go, ecc/stark-curve/ecdsa/marshal.go, internal/generator/ecdsa/template/ecdsa.go.tmpl, internal/generator/ecdsa/template/marshal.go.tmpl
I referred to other implementations to understand how v is computed when creating an ECDSA signature. I had assumed that v gives if `y` coordinate of the ephemeral point is small or large (e.h. bigger than half the order). But due to different encoding order, it was actually the oddity of `y`.
This is confirmed also in [Ethereum Yellow paper](https://ethereum.github.io/yellowpaper/paper.pdf) (Appendix F) and makes also a lot more sense.
=> feat: fix v computation in ECDSA signature

ecc/bn254/fr/sis/sis.go, ecc/bn254/fr/sis/sis.sage, ecc/bn254/fr/sis/sis_test.go
This PR updates the way we decompose a list of field elements into limbs.
The field elements were concatenated into bytes buffer in big-endian form and this bytes buffer was then split into limbs of short norm. The issue with this approach is that some limbs may contain bits from different field elements of the input slice. 
These are blockers for the self-recursion. Indeed, for self-recursion we critically rely on the fact that we can recompute the original field element from its limbs as a polynomial evaluation.
We split a slice of bytes representing an array of serialized field element in big-endian form into an array of limbs representing the same field elements in little-endian form. For instance, say our field is represented with 64 bits and we have the following field element `x = …
=> Update the limb decomposition of the SIS

ecc/secp256k1/fp/element.go, ecc/secp256k1/fr/element.go, field/generator/internal/templates/element/base.go
The staticcheck linter pointed out some unnecessary XORs with zero:
```
ecc/secp256k1/fr/element.go:235:10: SA4016: z[3] ^ 0 always equals z[3] (staticcheck)
return (z[3] ^ 0 | z[2] ^ 1 | z[1] ^ 4994812053365940164 | z[0] ^ 4624529908474429119) == 0
ecc/secp256k1/fp/element.go:235:10: SA4016: z[3] ^ 0 | z[2] ^ 0 | z[1] ^ 0 always equals z[3] ^ 0 | z[2] ^ 0 | z[1] (staticcheck)
return (z[3] ^ 0 | z[2] ^ 0 | z[1] ^ 0 | z[0] ^ 4294968273) == 0
```
This PR removes those.
=> Do not XOR with zero

.golangci.yml, ecc/bls12-377/fr/polynomial/pool.go, ecc/bls12-378/fr/polynomial/pool.go, ecc/bls12-381/fr/polynomial/pool.go, ecc/bls24-315/fr/polynomial/pool.go, ecc/bls24-317/fr/polynomial/pool.go, ecc/bn254/fr/polynomial/pool.go, ecc/bw6-633/fr/polynomial/pool.go, ecc/bw6-756/fr/polynomial/pool.go, ecc/bw6-761/fr/polynomial/pool.go, internal/generator/polynomial/template/pool.go.tmpl
This PR removes the `linter-settings` block which enables `check-shadowing`. Personally, I don't find this check all that useful; it's not necessarily dangerous and making new variables like `err2` and `err3` is pretty ugly IMO.
=> Disable check shadowing in govet linter

.golangci.yml, ecc/stark-curve/pedersen-hash/pedersen_hash_test.go, internal/bench/main.go
Enable the `misspell` linter which identifies common typos. There were only 3 findings.
=> Enable misspell linter & fix findings

ecc/bn254/fr/sis/sis.go
`CopyWithFreshBuffer` is a method of `RSis` whose intended role is to enable hashing in parallel by creating short-lived "clones" of the key. The present PR fixes a bug related to this.
Prior to this PR, `CopyWithFreshBuffer` would shallow copy the private fields `bufM`, `bufRes` and `bufMValues`. As a result, attempting to use several copies of the same key concurrently results in a race condition (the same buffer being used by all the threads at the same time). 
The proposed fix is to also initialize the rest of the buffers
```
res.bufM = make(fr.Vector, len(r.bufM))
res.bufMValues = bitset.New(r.bufMValues.Len())
res.bufRes = make(fr.Vector, len(r.bufRes))
```
=> Fix `RSis.CopyWithFreshBuffer`

ecc/bls12-377/marshal.go, ecc/bls12-378/marshal.go, ecc/bls12-381/marshal.go, ecc/bls24-315/marshal.go, ecc/bls24-317/marshal.go, ecc/bn254/marshal.go, ecc/bw6-633/marshal.go, ecc/bw6-756/marshal.go, ecc/bw6-761/marshal.go, internal/generator/ecc/template/marshal.go.tmpl
This is technically not a major problem, it only causes problems with serialization tests.
=> fix: do not read empty slices as nil

ecc/bls12-377/twistededwards/point.go, ecc/bls12-377/twistededwards/point_test.go, ecc/bls12-378/twistededwards/point.go, ecc/bls12-378/twistededwards/point_test.go, ecc/bls12-381/bandersnatch/point.go, ecc/bls12-381/bandersnatch/point_test.go, ecc/bls12-381/twistededwards/point.go, ecc/bls12-381/twistededwards/point_test.go, ecc/bls24-315/twistededwards/point.go, ecc/bls24-315/twistededwards/point_test.go, ecc/bls24-317/twistededwards/point.go, ecc/bls24-317/twistededwards/point_test.go, ecc/bn254/twistededwards/point.go, ecc/bn254/twistededwards/point_test.go, ecc/bw6-633/twistededwards/point.go, ecc/bw6-633/twistededwards/point_test.go, ecc/bw6-756/twistededwards/point.go, ecc/bw6-756/twistededwards/point_test.go, ecc/bw6-761/twistededwards/point.go, ecc/bw6-761/twistededwards/point_test.go, internal/generator/edwards/template/point.go.tmpl, internal/generator/edwards/template/tests/point.go.tmpl
This PR adds benchmarks for `Neg(...)` of points in Edwards variants, and an optimization to avoid redundant assignment in point coordinates.
If we run the new benchmarks available in the second commit of this branch against the same ones after the optimization here's what we get:
```
name               old time/op  new time/op  delta
pkg:github.com/consensys/gnark-crypto/ecc/bls12-377/twistededwards goos:linux goarch:amd64
Neg/Affine-16      4.60ns ± 2%  2.23ns ± 2%  -51.59%  (p=0.008 n=5+5)
Neg/Projective-16  5.28ns ± 3%  2.24ns ± 1%  -57.60%  (p=0.008 n=5+5)
Neg/Extended-16    7.73ns ± 1%  5.02ns ± 6%  -35.04%  (p=0.008 n=5+5)
pkg:github.com/consensys/gnark-crypto/ecc/bls12-378/twistededwards goos:linux goarch:amd64
Neg/Affine-16      4.77ns ± 5%  2.23ns ± 2%  -53.33%  (p=0.008 n=5+5) …
```
=> edwards: optimize point negation

ecc/bls12-377/ecdsa/ecdsa.go, ecc/bls12-378/ecdsa/ecdsa.go, ecc/bls12-381/ecdsa/ecdsa.go, ecc/bls24-315/ecdsa/ecdsa.go, ecc/bls24-317/ecdsa/ecdsa.go, ecc/bn254/ecdsa/ecdsa.go, ecc/bw6-633/ecdsa/ecdsa.go, ecc/bw6-756/ecdsa/ecdsa.go, ecc/bw6-761/ecdsa/ecdsa.go, ecc/secp256k1/ecdsa/ecdsa.go, ecc/stark-curve/ecdsa/ecdsa.go, internal/generator/ecdsa/template/ecdsa.go.tmpl
=> fix: ECDSA HashToInt bytes-bits mismatch

ecc/bls12-377/fr/mimc/mimc.go, ecc/bls12-378/fr/mimc/mimc.go, ecc/bls12-381/fr/mimc/mimc.go, ecc/bls24-315/fr/mimc/mimc.go, ecc/bls24-317/fr/mimc/mimc.go, ecc/bn254/fr/mimc/mimc.go, ecc/bw6-633/fr/mimc/mimc.go, ecc/bw6-756/fr/mimc/mimc.go, ecc/bw6-761/fr/mimc/mimc.go, internal/generator/crypto/hash/mimc/template/mimc.go.tmpl
- `Reset` keeps the same buffer
- `tmp` is allocated once above the loop (turns out that the allocation is not optimized)
=> Small optimization over the memory usage of MiMC

ecc/bls12-377/fr/fft/domain.go, ecc/bls12-377/fr/fft/fft.go, ecc/bls12-378/fr/fft/domain.go, ecc/bls12-378/fr/fft/fft.go, ecc/bls12-381/fr/fft/domain.go, ecc/bls12-381/fr/fft/fft.go, ecc/bls24-315/fr/fft/domain.go, ecc/bls24-315/fr/fft/fft.go, ecc/bls24-317/fr/fft/domain.go, ecc/bls24-317/fr/fft/fft.go, ecc/bn254/fr/fft/domain.go, ecc/bn254/fr/fft/fft.go, ecc/bw6-633/fr/fft/domain.go, ecc/bw6-633/fr/fft/fft.go, ecc/bw6-756/fr/fft/domain.go, ecc/bw6-756/fr/fft/fft.go, ecc/bw6-761/fr/fft/domain.go, ecc/bw6-761/fr/fft/fft.go, internal/generator/fft/template/domain.go.tmpl, internal/generator/fft/template/fft.go.tmpl
This PR removes precompute of `CosetTableReversed` and `CosetTableInvReversed` in `fft.Domain`. 
In practice these can be accessed from `CosetTable` and `CosetTableInv` .
New version may result in slightly slower FFT on small domains. 
However, for large domains (think large plonk circuit), precomputing these and storing them in RAM contribute to a high memory load, hence the PR.
=> perf: improve fft domain  memory footprint

ecc/bls12-377/twistededwards/point.go, ecc/bls12-377/twistededwards/point_test.go, ecc/bls12-378/twistededwards/point.go, ecc/bls12-378/twistededwards/point_test.go, ecc/bls12-381/bandersnatch/point.go, ecc/bls12-381/bandersnatch/point_test.go, ecc/bls12-381/twistededwards/point.go, ecc/bls12-381/twistededwards/point_test.go, ecc/bls24-315/twistededwards/point.go, ecc/bls24-315/twistededwards/point_test.go, ecc/bls24-317/twistededwards/point.go, ecc/bls24-317/twistededwards/point_test.go, ecc/bn254/twistededwards/point.go, ecc/bn254/twistededwards/point_test.go, ecc/bw6-633/twistededwards/point.go, ecc/bw6-633/twistededwards/point_test.go, ecc/bw6-756/twistededwards/point.go, ecc/bw6-756/twistededwards/point_test.go, ecc/bw6-761/twistededwards/point.go, ecc/bw6-761/twistededwards/point_test.go, internal/generator/edwards/template/point.go.tmpl, internal/generator/edwards/template/tests/point.go.tmpl
This PR improves the performance if Edwards-related curves in methods: `Add`, `MixedAdd` and `IsOnCuve`. The crux of the problem is two indirect allocations produced by `GetEdwardsCurve(...)` call.
I’m pretty sure that, at least for `MixedAdd`, this is a regression since we didn’t have this allocation some version ago. While fixing it, I noticed this was also happening today for `Add` and `IsOnCuve`, so I’m unsure if those are regressions.
The benchmarks also surface a performance problem I’m not fixing in this PR to avoid convoluting topics. I’ll give a brief explanation in the benchmark section below.
This PR doesn’t change the logic or add new border cases, so existing tests cover correct behavior.
The three mentioned methods (`Add`, `MixedAdd` and `IsOnCurve`) didn’t have benchmarks …
=> edwards: improve the performance of Add, MixedAdd and IsOnCurve

ecc/bls12-377/twistededwards/point.go, ecc/bls12-378/twistededwards/point.go, ecc/bls12-381/bandersnatch/point.go, ecc/bls12-381/twistededwards/point.go, ecc/bls24-315/twistededwards/point.go, ecc/bls24-317/twistededwards/point.go, ecc/bn254/twistededwards/point.go, ecc/bw6-633/twistededwards/point.go, ecc/bw6-756/twistededwards/point.go, ecc/bw6-761/twistededwards/point.go, internal/generator/edwards/template/point.go.tmpl
This PR proposes solving a performance problem while doing `Add` in Edwards curves. 
The TL;DR of the problem is that this operation does an equality checking, which involves a very slow inversion.
This PR doesn’t change the logic or add new border cases, so existing tests cover correct behavior.
```
name                    old time/op    new time/op    delta
MixedAdd/Extended-16       221ns ± 2%     220ns ± 2%      ~     (p=0.393 n=10+10)
Add/Extended-16           3.70µs ± 1%    0.20µs ± 2%   -94.52%  (p=0.000 n=10+10)
name                    old alloc/op   new alloc/op   delta
MixedAdd/Extended-16       0.00B          0.00B           ~     (all equal)
Add/Extended-16            0.00B          0.00B           ~     (all equal)
name                    old allocs/op  new allocs/op  delta …
```
=> edwards: avoid inversions in Add in extended points

ecc/bls12-377/g1.go, ecc/bls12-377/g2.go, ecc/bls12-378/g1.go, ecc/bls12-378/g2.go, ecc/bls12-381/g1.go, ecc/bls12-381/g2.go, ecc/bls24-315/g1.go, ecc/bls24-315/g2.go, ecc/bls24-317/g1.go, ecc/bls24-317/g2.go, ecc/bn254/g1.go, ecc/bn254/g2.go, ecc/bw6-633/g1.go, ecc/bw6-633/g2.go, ecc/bw6-756/g1.go, ecc/bw6-756/g2.go, ecc/bw6-761/g1.go, ecc/bw6-761/g2.go, ecc/secp256k1/g1.go, internal/generator/ecc/template/point.go.tmpl
Minor clean up, pr #451 introduced a snippet that is not used (see https://github.com/Consensys/gnark-crypto/pull/451/files#r1347690325 ) .
=> clean: remove useless snippet in mulWindowed

.github/parse-tests.js, .github/workflows/pr.yml, .github/workflows/push.yml, .gotestfmt/downloads.gotpl, .gotestfmt/package.gotpl, ecc/utils_test.go, field/generator/generator_test.go
CI workflow change to access failed test outputs in SLack / Github PR .
=> ci: update ci workflows

internal/generator/main.go
Remove duplicate gkr generation calls.
Not tested. There was only duplicate calls to generation.
Not benchmarked.
=> fix: remove duplicate gkr template generation

ecc/bls12-377/kzg/kzg.go, ecc/bls12-377/kzg/kzg_test.go, ecc/bls12-377/kzg/marshal.go, ecc/bls12-378/kzg/kzg.go, ecc/bls12-378/kzg/kzg_test.go, ecc/bls12-378/kzg/marshal.go, ecc/bls12-381/kzg/kzg.go, ecc/bls12-381/kzg/kzg_test.go, ecc/bls12-381/kzg/marshal.go, ecc/bls24-315/kzg/kzg.go, ecc/bls24-315/kzg/kzg_test.go, ecc/bls24-315/kzg/marshal.go, ecc/bls24-317/kzg/kzg.go, ecc/bls24-317/kzg/kzg_test.go, ecc/bls24-317/kzg/marshal.go, ecc/bn254/kzg/kzg.go, ecc/bn254/kzg/kzg_test.go, ecc/bn254/kzg/marshal.go, ecc/bw6-633/kzg/kzg.go, ecc/bw6-633/kzg/kzg_test.go, ecc/bw6-633/kzg/marshal.go, ecc/bw6-756/kzg/kzg.go, ecc/bw6-756/kzg/kzg_test.go, ecc/bw6-756/kzg/marshal.go, ecc/bw6-761/kzg/kzg.go, ecc/bw6-761/kzg/kzg_test.go, ecc/bw6-761/kzg/marshal.go, internal/generator/kzg/template/kzg.go.tmpl, internal/generator/kzg/template/kzg.test.go.tmpl, internal/generator/kzg/template/marshal.go.tmpl
Re-introducing points `G1`, `G2` and `[α]G2` in KZG verification key after #466. This is needed in the Solidity Plonk verifier in gnark. My initial thought was to hardcode the values of the points' coordinates in solidity instead of calling the KZG package, but apparently (cc @ThomasPiellard) Linea (and Aztec) use a different `G1` point than `(1,2)` for BN254. We should also then use `ScalarMultiplication(x, G1)` instead of `ScalarMultiplicationBase(x)`. Anyway it should be flexible for users now.
Same current tests.
NA
=> Refactor: re-introduce points in KZG verification key

ecc/bls12-377/g1.go, ecc/bls12-377/g2.go, ecc/bls12-378/g1.go, ecc/bls12-378/g2.go, ecc/bls12-381/g1.go, ecc/bls12-381/g2.go, ecc/bls24-315/g1.go, ecc/bls24-315/g2.go, ecc/bls24-317/g1.go, ecc/bls24-317/g2.go, ecc/bn254/g1.go, ecc/bn254/g2.go, ecc/bw6-633/g1.go, ecc/bw6-633/g2.go, ecc/bw6-633/pairing.go, ecc/bw6-756/g1.go, ecc/bw6-756/g2.go, ecc/bw6-761/g1.go, ecc/bw6-761/g2.go, ecc/bw6-761/pairing.go, ecc/secp256k1/g1.go, internal/generator/ecc/template/point.go.tmpl
This PR optimizes the curve membership test `IsOnCurve()` for all curves on both G1 and G2, by:
Old `TestG1AffineIsOnCurve` and `TestG2AffineIsOnCurve`
e.g. BLS12-381 on AWS z1d.large:
`G1`  335 ns vs. **190.6** ns
`G2` 624 ns vs. **495.3** ns
Compared to [geth/kilic](https://github.com/ethereum/go-ethereum/tree/master/crypto/bls12381) (cc @asanso, @MariusVanDerWijden):
`G1` 320.7 ns vs. **190.6** ns
`G2` 917.9 ns vs. **495.3** ns
=> perf: optimize curve membership test

ecc/bls12-377/fr/pedersen/pedersen.go, ecc/bls12-377/fr/pedersen/pedersen_test.go, ecc/bls12-378/fr/pedersen/pedersen.go, ecc/bls12-378/fr/pedersen/pedersen_test.go, ecc/bls12-381/fr/pedersen/pedersen.go, ecc/bls12-381/fr/pedersen/pedersen_test.go, ecc/bls24-315/fr/pedersen/pedersen.go, ecc/bls24-315/fr/pedersen/pedersen_test.go, ecc/bls24-317/fr/pedersen/pedersen.go, ecc/bls24-317/fr/pedersen/pedersen_test.go, ecc/bn254/fr/pedersen/pedersen.go, ecc/bn254/fr/pedersen/pedersen_test.go, ecc/bw6-633/fr/pedersen/pedersen.go, ecc/bw6-633/fr/pedersen/pedersen_test.go, ecc/bw6-756/fr/pedersen/pedersen.go, ecc/bw6-756/fr/pedersen/pedersen_test.go, ecc/bw6-761/fr/pedersen/pedersen.go, ecc/bw6-761/fr/pedersen/pedersen_test.go, internal/generator/pedersen/template/pedersen.go.tmpl, internal/generator/pedersen/template/pedersen.test.go.tmpl
This PR makes `pedersen.VerifyingKey` fields (`G` and `GRootSigmaNeg`) public to be able to read/copy at `gnark/std/recursion/groth16/verifier.ValueOfVerifyingKey`
=> refactor: make pedersen vk fields public

ecc/bls12-377/fr/gkr/gkr.go, ecc/bls12-377/fr/gkr/gkr_test.go, ecc/bls12-378/fr/gkr/gkr.go, ecc/bls12-378/fr/gkr/gkr_test.go, ecc/bls12-381/fr/gkr/gkr.go, ecc/bls12-381/fr/gkr/gkr_test.go, ecc/bls24-315/fr/gkr/gkr.go, ecc/bls24-315/fr/gkr/gkr_test.go, ecc/bls24-317/fr/gkr/gkr.go, ecc/bls24-317/fr/gkr/gkr_test.go, ecc/bn254/fr/gkr/gkr.go, ecc/bn254/fr/gkr/gkr_test.go, ecc/bw6-633/fr/gkr/gkr.go, ecc/bw6-633/fr/gkr/gkr_test.go, ecc/bw6-756/fr/gkr/gkr.go, ecc/bw6-756/fr/gkr/gkr_test.go, ecc/bw6-761/fr/gkr/gkr.go, ecc/bw6-761/fr/gkr/gkr_test.go, internal/generator/gkr/template/gkr.go.tmpl, internal/generator/gkr/template/gkr.test.go.tmpl, internal/generator/test_vector_utils/small_rational/gkr/gkr.go
This PR addresses a bug in the `gkr` package related to the `Evaluate` function of the `AddGate`. The existing logic within the AddGate evaluation function had an error that caused incorrect addition behavior under certain input scenarios. In addition to fixing the bug, this PR includes related tests as well.
https://github.com/Consensys/gnark-crypto/blob/d72fcb379d3eb894fc18ece74a91f835294e1439/ecc/bn254/fr/gkr/gkr.go#L881-L894
=> fix: gkr add gate evaluate

ecc/bn254/ecdsa/ecdsa.go, ecc/bn254/ecdsa/marshal.go, ecc/secp256k1/ecdsa/ecdsa.go, ecc/secp256k1/ecdsa/marshal.go, ecc/stark-curve/ecdsa/ecdsa.go, ecc/stark-curve/ecdsa/marshal.go, internal/generator/ecdsa/template/ecdsa.go.tmpl, internal/generator/ecdsa/template/marshal.go.tmpl
This PR returns error constants when ECDSA signature is invalid due to `r^3 + ax + b` being quadratic non-residue. This is used in gnark for handling edge cases. This also allows to make an internal method private.
=> feat: ECDSA error types

ecc/bls12-377/kzg/kzg_test.go, ecc/bls12-377/kzg/marshal.go, ecc/bls12-378/kzg/kzg_test.go, ecc/bls12-378/kzg/marshal.go, ecc/bls12-381/kzg/kzg_test.go, ecc/bls12-381/kzg/marshal.go, ecc/bls24-315/kzg/kzg_test.go, ecc/bls24-315/kzg/marshal.go, ecc/bls24-317/kzg/kzg_test.go, ecc/bls24-317/kzg/marshal.go, ecc/bn254/kzg/kzg_test.go, ecc/bn254/kzg/marshal.go, ecc/bw6-633/kzg/kzg_test.go, ecc/bw6-633/kzg/marshal.go, ecc/bw6-756/kzg/kzg_test.go, ecc/bw6-756/kzg/marshal.go, ecc/bw6-761/kzg/kzg_test.go, ecc/bw6-761/kzg/marshal.go, internal/generator/kzg/template/kzg.test.go.tmpl, internal/generator/kzg/template/marshal.go.tmpl, kzg/kzg.go, utils/testing.go
TLDR; adds a method (no breaking changes) to `kzg.SRS` object that quickly dumps a binary representation without doing any checks, and optionally, enables to truncate the SRS at writing / reading time. `UnsafeFromBytes` is 6x time faster than `UnsafeReadFrom` 
godoc:
```
// UnsafeToBytes returns the binary encoding of the entire SRS memory representation
// It is meant to be use to achieve fast serialization/deserialization and
// is not compatible with WriteTo / ReadFrom. It does not do any validation
// and doesn't encode points in a canonical form.
// @unstable: the format may change in the future
// If maxPkPoints is provided, the number of points in the ProvingKey will be limited to maxPkPoints
func (srs *SRS) UnsafeToBytes(maxPkPoints ...int) ([]byte, error) {
```
benchmark, 1 <<24 …
=> perf: add kzg.UnsafeToBytes and kzg.UnsafeFromBytes methods

ecc/bls12-377/fr/pedersen/pedersen_test.go, ecc/bls12-377/kzg/kzg_test.go, ecc/bls12-378/fr/pedersen/pedersen_test.go, ecc/bls12-378/kzg/kzg_test.go, ecc/bls12-381/fr/pedersen/pedersen_test.go, ecc/bls12-381/kzg/kzg_test.go, ecc/bls24-315/fr/pedersen/pedersen_test.go, ecc/bls24-315/kzg/kzg_test.go, ecc/bls24-317/fr/pedersen/pedersen_test.go, ecc/bls24-317/kzg/kzg_test.go, ecc/bn254/fr/pedersen/pedersen_test.go, ecc/bn254/kzg/kzg_test.go, ecc/bw6-633/fr/pedersen/pedersen_test.go, ecc/bw6-633/kzg/kzg_test.go, ecc/bw6-756/fr/pedersen/pedersen_test.go, ecc/bw6-756/kzg/kzg_test.go, ecc/bw6-761/fr/pedersen/pedersen_test.go, ecc/bw6-761/kzg/kzg_test.go, internal/generator/kzg/template/kzg.test.go.tmpl, internal/generator/pedersen/template/pedersen.test.go.tmpl, utils/testutils/testing.go
Previous state forced any package that imported `utils` (meaning a lot...) to import test stuff as side effect, and for example forced binaries building on top of gnark/gnark-crypto to embed testify/...
=> refactor: move test utils package into isolation to avoid every user to import test stuff

ecc/bls12-377/fr/sis/sis.go, ecc/bls12-377/fr/sis/sis_test.go
LimbDecompose would not work correctly if the logTwoBound is larger than 8 and would silently skips the input bits corresponding to any bytes coming after the first in every limb.
Fixes # (issue)
=> fix: sis limb-decomposition works with log-two_bound > 8

ecc/bw6-633/internal/fptower/e3.go, ecc/bw6-633/internal/fptower/e3_test.go, ecc/bw6-756/internal/fptower/e3.go, ecc/bw6-756/internal/fptower/e3_test.go, ecc/bw6-761/internal/fptower/e3.go, ecc/bw6-761/internal/fptower/e3_test.go
`Conjugate` in `Fp3` for BW6-761, BW6-756 and BW6-633 are incorrect but they are not used anywhere. This PR removes the corresponding code.
`Conjugate` tests are removed too.
N/A
=> refactor: remove E3 Conjugate from BW6

ecc/bn254/pairing.go, ecc/bw6-761/pairing.go
In affine pairing (`MillerLoopFixedQ`), use `doubleAndAdd` to compute `2P+Q` as of `P+Q+P`. This optimizes the one-time line precomputation for KZG in gnark-crypto, but most importantly matches gnark in-circuit implementation. This is now important since after https://github.com/Consensys/gnark/pull/1143 we need to have the exact same lines so that the witness residue is the same.
pairing tests pass.
In gnark-crypto, only the lines precompuation should be affected (faster) but it's just a one-time computation.
=> perf(bn254): optimize affine pairing with doubleAndAdd

ecc/bls12-377/fr/fri/fri_test.go, ecc/bls12-378/fr/fri/fri_test.go, ecc/bls12-381/fr/fri/fri_test.go, ecc/bls24-315/fr/fri/fri_test.go, ecc/bls24-317/fr/fri/fri_test.go, ecc/bn254/fr/fri/fri_test.go, ecc/bw6-633/fr/fri/fri_test.go, ecc/bw6-756/fr/fri/fri_test.go, ecc/bw6-761/fr/fri/fri_test.go, internal/generator/fri/template/fri.test.go.tmpl
Fixes flaky test in FRI package. The test generator may output 0 as input, but the tests seem to fail then.
=> fix: flaky FRI test

ecc/bls12-377/twistededwards/point.go, ecc/bls12-378/twistededwards/point.go, ecc/bls12-381/bandersnatch/endomorpism.go, ecc/bls12-381/bandersnatch/point.go, ecc/bls12-381/bandersnatch/point_test.go, ecc/bls12-381/twistededwards/point.go, ecc/bls24-315/twistededwards/point.go, ecc/bls24-317/twistededwards/point.go, ecc/bn254/twistededwards/point.go, ecc/bw6-633/twistededwards/point.go, ecc/bw6-756/twistededwards/point.go, ecc/bw6-761/twistededwards/point.go, internal/generator/edwards/template/point.go.tmpl, internal/generator/edwards/template/tests/point.go.tmpl
When we revisited GLV scalar decomposition https://github.com/Consensys/gnark-crypto/pull/213, we increased conditionally the loop bounds by 1 for all `mulGLV` methods for all curves but we forgot to do so for Bandersnatch twisted Edwards curve. This PR fixes the issue. 
added `scalarMulWindowed` which does a windowed double-and-add and compares the result with `scalarMulGLV` which uses the endomorphism. The method `ScalarMultiplication` picks `scalarMulGLV` whenever an efficient endomorphism is available (currently only for Bandersnatch).
```
benchmark                          old ns/op     new ns/op     delta
BenchmarkScalarMulExtended-8       30378         30271         -0.35%
BenchmarkScalarMulProjective-8     33844         33941         +0.29%
```
No major diff for random scalars.
=> fix(bandersnatch): GLV bounds + test

ecc/bls12-377/g2.go, ecc/bls12-378/g2.go, ecc/bls12-381/g2.go, ecc/bls24-315/g2.go, ecc/bls24-317/g2.go, ecc/bn254/g2.go, ecc/bw6-633/g2.go, ecc/bw6-756/g2.go, ecc/bw6-761/g2.go, internal/generator/ecc/template/point.go.tmpl
=> chore: fix some function names

ecc/bls12-377/fr/fft/fft.go, ecc/bls12-377/fr/fft/fft_test.go, ecc/bls12-378/fr/fft/fft.go, ecc/bls12-378/fr/fft/fft_test.go, ecc/bls12-381/fr/fft/fft.go, ecc/bls12-381/fr/fft/fft_test.go, ecc/bls24-315/fr/fft/fft.go, ecc/bls24-315/fr/fft/fft_test.go, ecc/bls24-317/fr/fft/fft.go, ecc/bls24-317/fr/fft/fft_test.go, ecc/bn254/fr/fft/fft.go, ecc/bn254/fr/fft/fft_test.go, ecc/bw6-633/fr/fft/fft.go, ecc/bw6-633/fr/fft/fft_test.go, ecc/bw6-756/fr/fft/fft.go, ecc/bw6-756/fr/fft/fft_test.go, ecc/bw6-761/fr/fft/fft.go, ecc/bw6-761/fr/fft/fft_test.go, internal/generator/fft/template/fft.go.tmpl, internal/generator/fft/template/tests/fft.go.tmpl
=> fix: fixes #522 with bound check before computing twiddles when domain has no precompute set

ecc/bls12-377/pairing.go, ecc/bls12-381/pairing.go
Similar to #506 for BLS12-377 and BLS12-381.
Existing tests pass.
```
+ [BLS12-*] Pair should output the same result with MillerLoop or MillerLoopFixedQ: OK, passed 100 tests.
```
Lines precomputations should be faster, but this is a one-time computation.
=> refactor(bls12-381, bls12-377): MillerLoopFixed corresponds to gnark

ecc/bls12-377/shplonk/shplonk.go, ecc/bls12-381/shplonk/shplonk.go, ecc/bls24-315/shplonk/shplonk.go, ecc/bls24-317/shplonk/shplonk.go, ecc/bn254/shplonk/shplonk.go, ecc/bw6-633/shplonk/shplonk.go, ecc/bw6-761/shplonk/shplonk.go, internal/generator/shplonk/template/shplonk.go.tmpl
At some point in shplonk batch opening we computed difference of two polynomials. But the buffer we subtracted from wasn't sufficiently big. Allocate now enough space.
=> fix: buffer sufficient size

ecc/bls12-377/fr/pedersen/pedersen.go, ecc/bls12-377/fr/pedersen/pedersen_test.go, ecc/bls12-381/fr/pedersen/pedersen.go, ecc/bls12-381/fr/pedersen/pedersen_test.go, ecc/bls24-315/fr/pedersen/pedersen.go, ecc/bls24-315/fr/pedersen/pedersen_test.go, ecc/bls24-317/fr/pedersen/pedersen.go, ecc/bls24-317/fr/pedersen/pedersen_test.go, ecc/bn254/fr/pedersen/pedersen.go, ecc/bn254/fr/pedersen/pedersen_test.go, ecc/bw6-633/fr/pedersen/pedersen.go, ecc/bw6-633/fr/pedersen/pedersen_test.go, ecc/bw6-761/fr/pedersen/pedersen.go, ecc/bw6-761/fr/pedersen/pedersen_test.go, internal/generator/pedersen/template/pedersen.go.tmpl, internal/generator/pedersen/template/pedersen.test.go.tmpl
This PR changes a variable's name to reflect its content more accurately.
=> GSigma -> GSigmaNeg

ecc/bls12-377/g1.go, ecc/bls12-377/g1_test.go, ecc/bls12-377/g2.go, ecc/bls12-377/g2_test.go, ecc/bls12-381/g1.go, ecc/bls12-381/g1_test.go, ecc/bls12-381/g2.go, ecc/bls12-381/g2_test.go, ecc/bls24-315/g1.go, ecc/bls24-315/g1_test.go, ecc/bls24-315/g2.go, ecc/bls24-315/g2_test.go, ecc/bls24-317/g1.go, ecc/bls24-317/g1_test.go, ecc/bls24-317/g2.go, ecc/bls24-317/g2_test.go, ecc/bn254/g1_test.go, ecc/bn254/g2.go, ecc/bn254/g2_test.go, ecc/bw6-633/g1.go, ecc/bw6-633/g1_test.go, ecc/bw6-633/g2.go, ecc/bw6-633/g2_test.go, ecc/bw6-761/g1.go, ecc/bw6-761/g1_test.go, ecc/bw6-761/g2.go, ecc/bw6-761/g2_test.go, ecc/secp256k1/g1_test.go, internal/generator/ecc/template/point.go.tmpl, internal/generator/ecc/template/tests/point.go.tmpl
use `mulWindowed` instead of `ScalarMultiplication` is G1 and G2 subgroup membership and cofactor clearing methods. 
1- The point is still purported to be in the prime subgroup where GLV applies
2- multiplying by a small constant is faster with `mulWindowed` 
N.B.: multiplying e.g. twice by `x0` is faster than multiplying by `x0^2` because it has smaller Hamming weight. E.g. for BLS12-381, `mul-by-x0` is 64 dbl + 6 mul while `mul-by-x0^2` is 128 dbl + 17 mul. There is still room for improvement if needed by specialising `mul-by-x0` using a short addition chain.
Same tests.
- BLS12-38
```
benchmark                        old ns/op     new ns/op     delta
BenchmarkG1JacIsInSubGroup-2     59891         46740         -21.96%
```
```
benchmark …
```
=> perf: subgroup check

ecc/bls12-377/fr/fri/fri_test.go, ecc/bls12-381/fr/fri/fri_test.go, ecc/bls24-315/fr/fri/fri_test.go, ecc/bls24-317/fr/fri/fri_test.go, ecc/bn254/fr/fri/fri_test.go, ecc/bw6-633/fr/fri/fri_test.go, ecc/bw6-761/fr/fri/fri_test.go, internal/generator/fri/template/fri.test.go.tmpl
fix some function names in comment
=> chore: fix some function names in comment

ecc/bls12-377/fp/element.go, ecc/bls12-377/fr/element.go, ecc/bls12-381/fp/element.go, ecc/bls12-381/fr/element.go, ecc/bls24-315/fp/element.go, ecc/bls24-315/fr/element.go, ecc/bls24-317/fp/element.go, ecc/bls24-317/fr/element.go, ecc/bn254/fp/element.go, ecc/bn254/fr/element.go, ecc/bw6-633/fp/element.go, ecc/bw6-633/fr/element.go, ecc/bw6-761/fp/element.go, ecc/bw6-761/fr/element.go, ecc/secp256k1/fp/element.go, ecc/secp256k1/fr/element.go, ecc/stark-curve/fp/element.go, ecc/stark-curve/fr/element.go, field/generator/internal/templates/element/conv.go, field/goldilocks/element.go
We can only conclude `v >= 0` instead of `v > 0` from `v.Cmp(&zero) != -1`.
=> fix comment of v for `SetBigInt`

field/generator/config/field_config.go, field/generator/generator_asm.go, field/generator/options.go
To avoid breaking changes on caller side, small fields (< 31bits) will still generate uint64 arith for now.
=> feat: generate uint32 arith only for babybear and koalabear

ecc/bls12-377/fflonk/fflonk.go, ecc/bls12-381/fflonk/fflonk.go, ecc/bls24-315/fflonk/fflonk.go, ecc/bls24-317/fflonk/fflonk.go, ecc/bn254/fflonk/fflonk.go, ecc/bw6-633/fflonk/fflonk.go, ecc/bw6-761/fflonk/fflonk.go, internal/generator/fflonk/template/fflonk.go.tmpl
- `ecc/bls12-377/fflonk/fflonk.go:156`: "opeings" corrected to "openings".
- Improved code accuracy and maintained professionalism.
=> typo-Update fflonk.go

ecc/bw6-761/internal/fptower/e6_direct.go, ecc/bw6-761/internal/fptower/e6_direct_test.go, ecc/bw6-761/pairing.go, ecc/bw6-761/pairing_test.go, internal/generator/pairing/template/tests/pairing.go.tmpl
This corresponds to the [gnark circuit](https://github.com/Consensys/gnark/blob/cfa30d90b1a438da4551c01c88ddea0c38aacb37/std/algebra/emulated/sw_bw6761/pairing.go#L253) and is needed to compute the same `residueWitness` in- and out-circuit for https://github.com/Consensys/gnark/pull/1365.
Added tests for the new `E6D` struct in `internal/fptower/e6_direct_test.go` and pairing computation using towered and direct extensions in `pairing_test.go`.
`MillerLoopDirect` is much slower than `MillerLoop` but it is only used in the hint computation for the gnark circuit.
```
benchmark                 tower ns/op   direct ns/op     delta …
```
=> feat(bw6-761): Miller loop using direct sextic extension

field/generator/asm/amd64/build.go, field/generator/asm/arm64/build.go, field/generator/internal/addchain/addchain.go, go.mod, go.sum, internal/generator/gkr/template/gkr.test.vectors.gen.go.tmpl, internal/generator/gkr/test_vectors/main.go
Update bavard to https://github.com/Consensys/bavard/pull/11 . 
Enables running `BAVARD=fft go generate ./...` or `BAVARD=koalabear go generate ./...` to generate only files whose output path contains the env var filter.
=> build: update to latest bavard, paralellize addchain read

ecc/bls12-377/fr/sis/sis.go, field/generator/internal/templates/sis/sis.go.tmpl, utils/max.go
Fixing an issue when setting SIS parameters w/ log2(bound) == 8 and log2(degree) == 6.
=> fix: ensure fast path is taken only with fixed bound and degree

ecc/bls12-377/g1_test.go, ecc/bls12-377/g2_test.go, ecc/bls12-381/g1.go, ecc/bls12-381/g1_test.go, ecc/bls12-381/g2.go, ecc/bls12-381/g2_test.go, ecc/bls24-315/g1_test.go, ecc/bls24-315/g2_test.go, ecc/bls24-317/g1_test.go, ecc/bls24-317/g2_test.go, ecc/bn254/g1_test.go, ecc/bn254/g2.go, ecc/bn254/g2_test.go, ecc/bw6-633/g1_test.go, ecc/bw6-633/g2_test.go, ecc/bw6-761/g1_test.go, ecc/bw6-761/g2_test.go, ecc/grumpkin/g1_test.go, ecc/secp256k1/g1_test.go, internal/generator/ecc/template/point.go.tmpl, internal/generator/ecc/template/tests/point.go.tmpl
- Generate test points that are intentionally on the G1/2 cofactor-torsions for fuzzing purposes. 
- Renamed some test methods to make more sense.
This is useful for geth fuzzer for bn254 and bls12-381. We could also generify the test for other curves but it's not a priority now IMO.
Last test in `TestIsOnG2` generates points (using `fuzzCofactorOfG*Jac`) that pass the `IsOnCurve` test but not `IsInSubGroup` test.
N/A
=> test(bn254, bls12-381): test points intentionally not on sugroups G1/2

field/babybear/extensions/e2.go, field/babybear/extensions/e4.go, field/babybear/extensions/e4_test.go, field/generator/internal/templates/extensions/e2.go.tmpl, field/generator/internal/templates/extensions/e4.go.tmpl, field/generator/internal/templates/extensions/e4_test.go.tmpl, field/goldilocks/extensions/e2.go, field/koalabear/extensions/e2.go, field/koalabear/extensions/e4.go, field/koalabear/extensions/e4_test.go
At least for small fields, the copy is useless / hurts perf. Likely same for other towers?
```
benchmark                      old ns/op     new ns/op     delta
BenchmarkE4MulByElement-16     6.74          5.95          -11.79%
BenchmarkE4MulByElement-16     6.76          5.86          -13.29%
```
=> perf: remove useless copies in e4 mul by elem

hash/merkle-damgard.go
`SetState` on a StateStorer now ensures that the size of the provided state corresponds to BlockSize.
=> feat: set default size for state

field/eisenstein/eisenstein.go, field/eisenstein/eisenstein_test.go
Some optimisations for Eisenstein arithmetic. This saves -50% for Half-GCD which we use in hints for emulated scalar multiplications in gnark.
Existing tests pass + test for new method `MulByConjugate`.
Macbook Air M1:
```
benchmark              old ns/op     new ns/op     delta
BenchmarkHalfGCD-8     74454         36803         -50.57%
BenchmarkMul-8         175           113           -35.17%
BenchmarkNorm-8        109           60.2          -44.93%
BenchmarkQuoRem-8      1034          396           -61.69%
```
=> perf: optimize Eisenstein arithmetic

ecc/bls12-377/g1.go, ecc/bls12-377/g2.go, ecc/bls12-381/g1.go, ecc/bls12-381/g2.go, ecc/bls24-315/g1.go, ecc/bls24-315/g2.go, ecc/bls24-317/g1.go, ecc/bls24-317/g2.go, ecc/bn254/g1.go, ecc/bn254/g2.go, ecc/bw6-633/g1.go, ecc/bw6-633/g2.go, ecc/bw6-761/g1.go, ecc/bw6-761/g2.go, ecc/grumpkin/g1.go, ecc/secp256k1/g1.go, internal/generator/ecc/template/point.go.tmpl
This PR corrects comments (URL to EFD forumulas) and saves `2m` in Jacobian doubling and `3m` in extended Jacobian mixed doubling.
Current tests pass.
e.g. BLS12-381 on MBA M1:
```
benchmark                  old ns/op     new ns/op     delta
BenchmarkG1JacDouble-8     338           298           -11.76%
```
=> perf: Doubling and mixed doubling in Jacobians and ext. Jacobians

field/babybear/extensions/e4_test.go, field/babybear/extensions/vector.go, field/generator/internal/templates/extensions/e4_test.go.tmpl, field/generator/internal/templates/extensions/vector.go.tmpl, field/koalabear/extensions/e4_test.go, field/koalabear/extensions/vector.go, internal/parallel/execute.go
Adds a parallel prefix product method for e4 vectors. 
```
cpu: AMD EPYC 9R14
BenchmarkPrefixProduct/generic-96                     84          14388851 ns/op               0 B/op          0 allocs/op
BenchmarkPrefixProduct/PrefixProduct-96             1026           1150196 ns/op           21797 B/op        298 allocs/op
```
=> feat: add parallel prefix product for vector e4
